### ISSUE TITLE
Pagination Implementation

### ISSUE THREAD

**Issue by maestro-00** [Lukada-taiya/Frenzy#2]
Endpoint on homepage  paginates movie result set.

**Describe the solution you'd like**
The 'page' parameter should be passed to the endpoint to specify which page should be shown. 
Take into consideration the totalResults key of the result set

Api Documentation : [Omdb Api](https://www.omdbapi.com/)

**Comment by Yashop181** [comment]
Hi @Lukada-taiya,

I'd like to take on this issue and implement the pagination for the movie result set on the homepage. I'll ensure the page parameter is passed to the endpoint to fetch the appropriate results and take into account the totalResults key to calculate the total number of pages.

Here's a summary of what I plan to do:

Modify the API call to include the page parameter.
Calculate the total number of pages based on the totalResults key.
Implement pagination controls to navigate between pages.

Thanks!

**Comment by maestro-00** [comment]
Have at it then

**Comment by Yashop181** [comment]
Hi @Lukada-taiya,

Thank you for assigning me this task. I'll start working on the pagination implementation for the movie result set on the homepage right away.

Here's my plan:

-Modify the API Call: Update the API call to include the page parameter to fetch the correct set of results.

-Calculate Total Pages: Use the totalResults key to determine the total number of pages available.

-Implement Pagination Controls: Add controls to navigate between different pages, ensuring a smooth user experience.

-I'll keep you updated on my progress and reach out if I have any questions.

**Comment by maestro-00** [comment]
Fixed by PR #5
