### ISSUE TITLE
Feat: Enhanced Search

### ISSUE THREAD

**Issue by maestro-00** [Lukada-taiya/Frenzy#7]
The search bar on the home page only allows you to search by the movie title. There should be an option to choose the movie type you are searching by and also the year.

The Api endpoint used to retrieve the movies takes a 'type' and a 'y' parameter. 
- Add an input field for the user to search according to which year movie was released.
- Add a type selectbox, to the search, for the user to choose what to search by.(SelectBox Options: movie, series, episode,game)

Movie Api Used: [Omdb Api](https://www.omdbapi.com/)

**Comment by ChiragShukla222** [comment]
Hey @Lukada-taiya , can you assign this issue to me

**Comment by maestro-00** [comment]
Okay. Its yours

**Comment by ChiragShukla222** [comment]
Hey @Lukada-taiya ,

I've solved the issue and added an option to choose the movie type you're searching for and also the year. Please check it out and let me know if there's anything else needed.

**Comment by maestro-00** [comment]
Create a pull request on the main branch please.

**Comment by ChiragShukla222** [comment]
I've created a pull request on the main branch please review it.

**Comment by maestro-00** [comment]
Hello, but I don't see your pull request. Did you create it on the repo

**Comment by ChiragShukla222** [comment]
Hey, I've created a pull request on the main branch and it's showing a "working tree clean"

**Comment by maestro-00** [comment]
Click this link to create the PR [link](https://github.com/Lukada-taiya/Frenzy/compare/master...ChiragShukla222:Frenzy:main)
Make sure you specify the branch your changes are on before creating the PR

**Comment by maestro-00** [comment]
Solve by PR #9
